package com.geekbrains.tests

const val ON_DELAY_MESSAGE = "Wait for ${DELAY / 1000} seconds"
const val SEARCH_QUERY = "UiAutomator"
const val EXPECTED_STRING = "Number of results:"
const val EXPECTED_SEARCHED_STRING = "$EXPECTED_STRING $RESULTS_COUNT"
const val EXPECTED_SEARCHED_STRING_AFTER_DECREMENT = "$EXPECTED_STRING ${RESULTS_COUNT - 1}"
const val EXPECTED_SEARCHED_STRING_AFTER_INCREMENT = "$EXPECTED_STRING ${RESULTS_COUNT + 1}"
const val EXPECTED_STRING_AFTER_DECREMENT_NO_SEARCH = "$EXPECTED_STRING -1"
const val EXPECTED_STRING_AFTER_INCREMENT_NO_SEARCH = "$EXPECTED_STRING 1"
const val EXPECTED_SEARCHED_STRING_ZERO = "$EXPECTED_STRING 0"
const val RESPONSE_IS_NULL_MESSAGE = "Response is null or unsuccessful"
const val SEARCH_RESULTS_ARE_NULL = "Search results or total count are null"